spring:
  application:
    name: "${APP_NAME:default-app-name}"

http:
  client:
    host: "${HTTP_CLIENT_HOST:defaulthttphost}"

database:
  password: "${DB_PASSWORD:default-db-pass}"

management:
  endpoint:
    health:
      probes.enabled: true
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
