apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: readiness
  name: readiness-http
  namespace: test
spec:
  containers:
    - name: readiness
      image: michalwit/boot-demo:006
      # livenessProbe and readinessProbe will wait until 'startupProbe' succeeded
      startupProbe:
        httpGet:
          path: /health
          port: 8080
          httpHeaders:
            - name: Probe
              value: startupProbe
        initialDelaySeconds: 0 # def: 0
        periodSeconds: 1 # def: 10
        failureThreshold: 60 # def: 3
      # should perform 'regular health check' = check only if the app is up (to prevent loop cycles)
      livenessProbe:
        httpGet:
          path: /health
          port: 8080
          httpHeaders:
            - name: Probe
              value: livenessProbe
        periodSeconds: 3
        failureThreshold: 5 # default is 3
      # should perform 'deep health check' = check dependencies
      readinessProbe:
        httpGet:
          path: /ready
          port: 8080
        periodSeconds: 3
        failureThreshold: 5 # default is 3
