apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: readiness
  name: readiness-http
  namespace: test
spec:
  initContainers:
    - name: init-myservice
      image: busybox:1.28
      #command: [ 'sh', '-c', "until nslookup myservice.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done" ]
      command: [ 'sh', '-c', "until nslookup myservice.test.svc.cluster.local; do echo waiting for myservice; sleep 2; done" ]
  containers:
    - name: app-container # application container = main container
      image: michalwit/boot-demo:008
      startupProbe:
        httpGet:
          path: /health
          port: 8080
        initialDelaySeconds: 0 # def: 0
        periodSeconds: 1 # def: 10
        failureThreshold: 60 # def: 3
      livenessProbe:
        httpGet:
          path: /health
          port: 8080
        periodSeconds: 3
        failureThreshold: 5 # default is 3=