apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: test
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template: # Pod spec
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: db-app
          image: michalwit/boot-demo:001
          ports:
            - containerPort: 8080
              name: s-boot-port
---
apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: test
spec:
  type: NodePort
  selector:
    app: demo # looks up for pods with this label
  ports:
    - protocol: TCP
      port: 8888
      targetPort: s-boot-port