apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: test
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template: # Pod spec
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: db-app
          image: michalwit/boot-demo:001
          ports:
            - containerPort: 8080
              name: s-boot-port
          env:
            - name: SPRING_APPLICATION_JSON
              valueFrom:
                  configMapKeyRef:
                    name: test
                    key: config_json
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: test
                  key: db-password

---
apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: test
  labels:
    app: demo
spec:
  type: NodePort
  selector:
    app: demo # looks up for pods with this label
  ports:
    - protocol: TCP
      port: 8888
      targetPort: s-boot-port
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ingress
  namespace: test
  labels:
    app: demo
spec:
  ingressClassName: nginx
  rules:
    - host: hello-world.example
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo
                port:
                  number: 8888
---
apiVersion: v1
kind: Secret
metadata:
  name: test
  namespace: test
type: Opaque
data:
  db-password: bXlwYXNzd29yZA==
