apiVersion: v1
kind: Service
metadata:
  name: {{ include "test-template.fullname" . }}
  namespace: test
  labels:
    {{- include "test-template.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "test-template.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: s-boot-port
