apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: v1
kind: Pod
metadata:
  name: on-failure-pod
  namespace: test
spec:
  restartPolicy: OnFailure
  containers:
    - name: on-failure-container  # This container will be restarted on failure.
      image: docker.io/library/busybox:1.28
      command: ['sh', '-c', 'echo "Keep restarting" && sleep 10 && exit 0']
---
apiVersion: v1
kind: Pod
metadata:
  name: always-pod
  namespace: test
spec:
  restartPolicy: Always
  containers:
    - name: always-container  # This container will be restarted on failure.
      image: docker.io/library/busybox:1.28
      command: ['sh', '-c', 'echo "Keep restarting" && sleep 10 && exit 0']
---
apiVersion: v1
kind: Pod
metadata:
  name: never-pod
  namespace: test
spec:
  restartPolicy: Never
  containers:
    - name: never-container  # This container will be restarted on failure.
      image: docker.io/library/busybox:1.28
      command: ['sh', '-c', 'echo "Keep restarting" && sleep 10 && exit 0']
