apiVersion: v1
kind: Namespace
metadata:
  name: test-cpu
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-cpu-deployment
  namespace: test-cpu
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template: # Pod spec
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: db-app
          image: michalwit/boot-demo:013
          resources:
            requests: # required by Keda CPU scaller ('resources.requests' or 'resources.limits' is needed)
              memory: "128Mi"
              cpu: "400m" # milliCPU (100m = 0.1) # fraction of available CPU cores on the node that the pod is scheduled on
          ports:
            - containerPort: 8080
              name: s-boot-port
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cpu-scaledobject
  namespace: test-cpu
spec:
  scaleTargetRef:
    name: test-cpu-deployment
  minReplicaCount: 1 # Optional. Default: 0
  maxReplicaCount: 10
  pollingInterval: 1 # default 30 - 30 s
  cooldownPeriod: 10 # default 300 - 300 s
  triggers:
    - type: cpu
      # Allowed types are 'Utilization' or 'AverageValue'
      metricType: Utilization  # represented as a percentage of the requested value of the resource for the pods
      metadata:
        value: "60"
---
apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: test-cpu
  labels:
    app: demo
spec:
  type: ClusterIP
  selector:
    app: demo # looks up for pods with this label
  ports:
    - protocol: TCP
      port: 8888
      targetPort: s-boot-port
