apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: test
  labels:
    app: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo
  template: # Pod spec
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: db-app
          image: michalwit/boot-demo:006
          ports:
            - containerPort: 8080
              name: s-boot-port
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: test
                  key: db-password
            - name: HTTP_CLIENT_HOST
              valueFrom:
                configMapKeyRef:
                  name: test-a-cm
                  key: http-client-host
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: test-a-cm
                  key: app-name

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-a-cm
  namespace: test
data:
  app-name: "demo-a"
  http-client-host: "demo-b"
---
apiVersion: v1
kind: Secret
metadata:
  name: test
  namespace: test
type: Opaque
data:
  db-password: bXlwYXNzd29yZA==
