apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-chart-demo.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helm-chart-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "helm-chart-demo.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: s-boot-port
