apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-irsa-demo
  region: sdf
  version: "1.33"
iam:
  withOIDC: true  # Required for IRSA
managedNodeGroups:
  - name: ng-1
    instanceType: t3.medium
    minSize: 2